version: '3.5'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: traveler:latest
    volumes:
      - .:/home/flask/project
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:11.0-alpine
    volumes:
      - traveler_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: unicorn_user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  traveler_db: