[tool.poetry]
name = "traveler"
version = "0.1.0"
description = ""
authors = ["Joe Huang"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.3"
flask-sqlalchemy = "^3.1.1"
voluptuous = "^0.15.2"
gunicorn = "^23.0.0"
delorean = "^1.0.0"
flask-migrate = "^4.0.7"
redis = "^5.0.8"
structlog = "^24.4.0"
pydantic = "^2.9.2"
tenacity = "^9.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-flask = "^1.3.0"
pytest-cov = "^5.0.0"
pytest-mock = "^3.14.0"
factory-boy = "^3.3.1"
pytest-redis = "^3.1.2"
fakeredis = "^2.24.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
